### ISSUE TITLE
Problem with a test

### ISSUE THREAD

**Issue by kitkazak** [WebPurple/external-courses#129]
Test for the first ex. won't pass due to name of the file must be named as "task-01.js" but it's said in description that if there is only one task to complete the file must be named as "task.js".

![1](https://user-images.githubusercontent.com/48328851/54279470-3655ef80-45a6-11e9-92b3-9d924a4f64f4.png)

![2](https://user-images.githubusercontent.com/48328851/54279475-3950e000-45a6-11e9-8282-ebee00f96399.png)

**Comment by k911mipt** [comment]
will be fixed after #130 approve
