### ISSUE TITLE
Travis test gives an error after commit stage

### ISSUE THREAD

**Issue by bartnar** [WebPurple/external-courses#149]
Cannot read property 'addExpectationResult' of undefined. Crashes at ex8
//////
const {task, css, html} = require('~utils')('ex8_html-css-basics', true, 'html');

describe('Ex8. HTML & CSS Basics', () => {
    const tasks = Array.from({length: 4}).map((_, i) => `0${i + 1}`);

    tasks.forEach(t =>
        task(t, markup => {
            it('html should be valid', html(markup));
            it('css should be valid', css(markup));
        }),
    );
});
//////
https://github.com/facebook/jest/issues/5922

**Comment by elenap1991** [comment]
Had same problem. Seems you have css validation fix. They fixed that at https://github.com/facebook/jest/pull/8005, you have to update jest version in your `package.json`, run `npm install` and update `package-lock.json` too, so travis would use new jest version. For example, i choosed to update to version `24.8.0`, it helped to discover real errors

**Comment by VladimirEliseev** [comment]
/home/travis/build/VladimirEliseev/external-courses/node_modules/jest-jasmine2/build/jasmine/Env.js:534
      currentRunnable().addExpectationResult(false, {
                       ^
TypeError: Cannot read property 'addExpectationResult' of undefined
    at Env.fail (/home/travis/build/VladimirEliseev/external-courses/node_modules/jest-jasmine2/build/jasmine/Env.js:534:24)
    at Function.next.fail (/home/travis/build/VladimirEliseev/external-courses/node_modules/jest-jasmine2/build/queue_runner.js:52:22)
    at fail (/home/travis/build/VladimirEliseev/external-courses/test-utils.js:71:37)
    at ValidationStream.<anonymous> (/home/travis/build/VladimirEliseev/external-courses/node_modules/css-validator/lib/css-validator.js:20:7)
    at ValidationStream.emit (events.js:210:5)
    at /home/travis/build/VladimirEliseev/external-courses/node_modules/css-validator/node_modules/readable-stream/lib/_stream_readable.js:934:16
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpurple-external-courses@1.0.0 test:ci: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpurple-external-courses@1.0.0 test:ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-11-08T11_55_45_531Z-debug.log
The command "npm run test:ci" exited with 1.

**Comment by VladimirEliseev** [comment]
При создании Pull request указывал на ошибку в каком-то файле из предыдущих заданий. Я его удалил, ошибка ушла. Потом обновил Pull request также выдал ошибку из предыдущих заданий, после удаления этих файлов возникла эта ошибка.

**Comment by VladimirEliseev** [comment]
https://github.com/VladimirEliseev/external-courses/pull/9

**Comment by eugrdn** [comment]
Fixed in #201
