### ISSUE TITLE
Travis fails due to 'jump-' keywords in steps() value of animation property

### ISSUE THREAD

**Issue by oldjunior** [WebPurple/external-courses#196]
I'm experiencing an issue with the pre-commit test in **ex11**:
> 1. “jump-both” is not a “animation” value : in .pizza
> 2. “jump-start” is not a “animation” value : in .pizza-fadeout

I'm aware that **jump-start** and **jump-both** are experimental features of **animation-timing-function** but I need them in my preloader to synchronize two animations. Could you, please, consider it some kind of progressive enhancement and add an exception to the test?

**Comment by oldjunior** [comment]
**UPD:** 'jump-' keywords are no longer experimental, acc. to MDN

**Comment by eugrdn** [comment]
We're using http://jigsaw.w3.org/css-validator API to check if CSS is correct.
Since it's not supported there yet, please use stable CSS syntax.
