### ISSUE TITLE
Travis CI: problem with the yarn.lock

### ISSUE THREAD

**Issue by aneelia** [WebPurple/external-courses#208]
yarn.lock was update today

<img width="915" alt="Screenshot 2020-02-28 at 00 46 33" src="https://user-images.githubusercontent.com/17769359/75489704-c82b5800-59c3-11ea-8108-988eddde81f3.png">

**Comment by ifedyukin** [comment]
@aneelia you must keep one lock file: package-lock.json or yarn.lock.
Just make choose and remove one of them.

**Comment by eugrdn** [comment]
Fixed in #209
