### ISSUE TITLE
Horisontal scroll on desctop(1800px width)

### ISSUE THREAD

**Issue by Ba888Ton** [WebPurple/external-courses#219]
https://learn.webpurple.net/externals/topic7_js-array-methods/js-array-methods#%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D1%8B

https://drive.google.com/file/d/1_xGtww3l1JibPzJ6e0sJ43_SsT7GQxCn/view?usp=drivesdk

**Comment by spiderpoul** [comment]
Seems works ok now
