### ISSUE TITLE
Fix ex3 - task 4 criteria or linter rules.

### ISSUE THREAD

**Issue by ZeninZenin** [WebPurple/external-courses#260]
[Ссылка на таску](https://github.com/WebPurple/external-courses/tree/master/src/ex3_js-objects-part1#%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-4)
Текст таски:

> Написать функцию, которая принимает строку и объект, проверяет есть ли у переданного объекта свойство с данным именем, если такое свойство отсутствует, то добавляет его и устанавливает значение 'new'. **Функция должна возвращать модифицированный исходный объект.**

По заданию, видно, что надо вернуть "модифицированный исходный объект". При этом, линтер не дает менять свойства параметра функции. Предлагаю требовать возвращать новый объект.

**Comment by aneelia** [comment]
@ZeninZenin ок, делай PR, я залью

**Comment by Valeripetrukhina** [comment]
если в задаче требовать возвращать новый объект, то тогда нужно переделать тест, так как он ожидает, что исходный объект мутирует 
![Безымянный](https://user-images.githubusercontent.com/79864824/111208956-7492a900-85dc-11eb-8cfa-fbfd7158a2a7.jpg)
