### ISSUE TITLE
Fix eslint problem in package.json

### ISSUE THREAD

**Issue by treger78** [WebPurple/external-courses#295]
Падают проверки Travis CI из-за ошибки Value for 'ext' of type '[String]' required.
В файле package.json в 7-ой строке изменил
`"lint": "eslint --ext --cache .js ./ --fix",`
на
`"lint": "eslint --ext .js --cache ./ --fix",`
проверки Travis CI перестали падать.

P. S. Также небольшая поправка по Readme - Начало работы - можно немного поправить 4-ый пункт:

-- 4. В настройках репозитория добавляем к репозиторию тренеров (Settings -> Collaborators);
++ 4. В настройках репозитория добавляем к репозиторию тренеров (Settings -> Manage access -> Invite a collaborator);

**Comment by spiderpoul** [comment]
fixed
